### ISSUE TITLE
GradCAM implementation 

### ISSUE THREAD

**Issue by guillaumejaume** [maragraziani/interpretAI_DigiPath#4]
- The GradCAM implementation includes lines of code that are commented - should they be removed?
- The comment ""GradCAM method for visualizing input saliency.""" should be placed right after the def command. 
- Suggestion: it would be nice to see the connection between each line and the GradCAM equations (the ones you present in the slides)
- Suggestion: using `cls` as a variable name is a bit dangerous as it is overwritting a native python keyword.

**Comment by maragraziani** [comment]
Hi, thanks! I addressed almost everything, I just did not add the equations. I think they are clear enough from the paper.
