### ISSUE TITLE
More viz in concept attribution

### ISSUE THREAD

**Issue by guillaumejaume** [maragraziani/interpretAI_DigiPath#6]
Suggestion: It would be nice to have more visual examples in the concept attribution notebook to understand what is the output. 

Nitpicking:
- some of the var are declared as `x=0` and other ones as `x = 0` (with spaces), better to unify as `x = 0`according to PEP8 guidelines
- some of the variables are defined with uppercase letters, eg `BATCH_SIZE`, and other ones with lowercase letters, eg, `seed`. I couldn't get the meaning of using one vs the other, better to unify. 
(but again nitpicking)

**Comment by maragraziani** [comment]
Yes, that was right.
