### ISSUE TITLE
Remove .DS_store

### ISSUE THREAD

**Issue by guillaumejaume** [maragraziani/interpretAI_DigiPath#8]
There are 2 .DS_store files that were pushed

**Comment by guillaumejaume** [comment]
Also remove the .ipynb_checkpoints file

**Comment by guillaumejaume** [comment]
Actually 2 more .DS_store in imgs and data to remove. 

Suggestion: add .DS_store to the .gitignore or make sure that you only add files one by one (e.g., no `git add .` / `git add -A`, `git add *`)

**Comment by maragraziani** [comment]
Done
